// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/Company.proto

package com.bonaparte.bean;

public final class CompanyProto {
  private CompanyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CompanysOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Companys)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Companys.Company companys = 1;</code>
     */
    java.util.List<com.bonaparte.bean.CompanyProto.Companys.Company> 
        getCompanysList();
    /**
     * <code>repeated .Companys.Company companys = 1;</code>
     */
    com.bonaparte.bean.CompanyProto.Companys.Company getCompanys(int index);
    /**
     * <code>repeated .Companys.Company companys = 1;</code>
     */
    int getCompanysCount();
    /**
     * <code>repeated .Companys.Company companys = 1;</code>
     */
    java.util.List<? extends com.bonaparte.bean.CompanyProto.Companys.CompanyOrBuilder> 
        getCompanysOrBuilderList();
    /**
     * <code>repeated .Companys.Company companys = 1;</code>
     */
    com.bonaparte.bean.CompanyProto.Companys.CompanyOrBuilder getCompanysOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Companys}
   */
  public  static final class Companys extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Companys)
      CompanysOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Companys.newBuilder() to construct.
    private Companys(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Companys() {
      companys_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Companys(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                companys_ = new java.util.ArrayList<com.bonaparte.bean.CompanyProto.Companys.Company>();
                mutable_bitField0_ |= 0x00000001;
              }
              companys_.add(
                  input.readMessage(com.bonaparte.bean.CompanyProto.Companys.Company.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          companys_ = java.util.Collections.unmodifiableList(companys_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bonaparte.bean.CompanyProto.internal_static_Companys_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bonaparte.bean.CompanyProto.internal_static_Companys_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bonaparte.bean.CompanyProto.Companys.class, com.bonaparte.bean.CompanyProto.Companys.Builder.class);
    }

    public interface CompanyOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Companys.Company)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int64 id = 1;</code>
       */
      long getId();

      /**
       * <code>string name = 2;</code>
       */
      java.lang.String getName();
      /**
       * <code>string name = 2;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>int64 memberCount = 3;</code>
       */
      long getMemberCount();

      /**
       * <code>repeated string aliasName = 4;</code>
       */
      java.util.List<java.lang.String>
          getAliasNameList();
      /**
       * <code>repeated string aliasName = 4;</code>
       */
      int getAliasNameCount();
      /**
       * <code>repeated string aliasName = 4;</code>
       */
      java.lang.String getAliasName(int index);
      /**
       * <code>repeated string aliasName = 4;</code>
       */
      com.google.protobuf.ByteString
          getAliasNameBytes(int index);
    }
    /**
     * Protobuf type {@code Companys.Company}
     */
    public  static final class Company extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Companys.Company)
        CompanyOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Company.newBuilder() to construct.
      private Company(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Company() {
        id_ = 0L;
        name_ = "";
        memberCount_ = 0L;
        aliasName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Company(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                id_ = input.readInt64();
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 24: {

                memberCount_ = input.readInt64();
                break;
              }
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();
                if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                  aliasName_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000008;
                }
                aliasName_.add(s);
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
            aliasName_ = aliasName_.getUnmodifiableView();
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bonaparte.bean.CompanyProto.internal_static_Companys_Company_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bonaparte.bean.CompanyProto.internal_static_Companys_Company_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bonaparte.bean.CompanyProto.Companys.Company.class, com.bonaparte.bean.CompanyProto.Companys.Company.Builder.class);
      }

      private int bitField0_;
      public static final int ID_FIELD_NUMBER = 1;
      private long id_;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }

      public static final int NAME_FIELD_NUMBER = 2;
      private volatile java.lang.Object name_;
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int MEMBERCOUNT_FIELD_NUMBER = 3;
      private long memberCount_;
      /**
       * <code>int64 memberCount = 3;</code>
       */
      public long getMemberCount() {
        return memberCount_;
      }

      public static final int ALIASNAME_FIELD_NUMBER = 4;
      private com.google.protobuf.LazyStringList aliasName_;
      /**
       * <code>repeated string aliasName = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getAliasNameList() {
        return aliasName_;
      }
      /**
       * <code>repeated string aliasName = 4;</code>
       */
      public int getAliasNameCount() {
        return aliasName_.size();
      }
      /**
       * <code>repeated string aliasName = 4;</code>
       */
      public java.lang.String getAliasName(int index) {
        return aliasName_.get(index);
      }
      /**
       * <code>repeated string aliasName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAliasNameBytes(int index) {
        return aliasName_.getByteString(index);
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (id_ != 0L) {
          output.writeInt64(1, id_);
        }
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
        }
        if (memberCount_ != 0L) {
          output.writeInt64(3, memberCount_);
        }
        for (int i = 0; i < aliasName_.size(); i++) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, aliasName_.getRaw(i));
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (id_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, id_);
        }
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
        }
        if (memberCount_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(3, memberCount_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < aliasName_.size(); i++) {
            dataSize += computeStringSizeNoTag(aliasName_.getRaw(i));
          }
          size += dataSize;
          size += 1 * getAliasNameList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.bonaparte.bean.CompanyProto.Companys.Company)) {
          return super.equals(obj);
        }
        com.bonaparte.bean.CompanyProto.Companys.Company other = (com.bonaparte.bean.CompanyProto.Companys.Company) obj;

        boolean result = true;
        result = result && (getId()
            == other.getId());
        result = result && getName()
            .equals(other.getName());
        result = result && (getMemberCount()
            == other.getMemberCount());
        result = result && getAliasNameList()
            .equals(other.getAliasNameList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (37 * hash) + MEMBERCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMemberCount());
        if (getAliasNameCount() > 0) {
          hash = (37 * hash) + ALIASNAME_FIELD_NUMBER;
          hash = (53 * hash) + getAliasNameList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.bonaparte.bean.CompanyProto.Companys.Company parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.bonaparte.bean.CompanyProto.Companys.Company parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.bonaparte.bean.CompanyProto.Companys.Company parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.bonaparte.bean.CompanyProto.Companys.Company parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.bonaparte.bean.CompanyProto.Companys.Company parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.bonaparte.bean.CompanyProto.Companys.Company parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.bonaparte.bean.CompanyProto.Companys.Company parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.bonaparte.bean.CompanyProto.Companys.Company parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.bonaparte.bean.CompanyProto.Companys.Company parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.bonaparte.bean.CompanyProto.Companys.Company parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.bonaparte.bean.CompanyProto.Companys.Company parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.bonaparte.bean.CompanyProto.Companys.Company parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.bonaparte.bean.CompanyProto.Companys.Company prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Companys.Company}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Companys.Company)
          com.bonaparte.bean.CompanyProto.Companys.CompanyOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.bonaparte.bean.CompanyProto.internal_static_Companys_Company_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.bonaparte.bean.CompanyProto.internal_static_Companys_Company_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.bonaparte.bean.CompanyProto.Companys.Company.class, com.bonaparte.bean.CompanyProto.Companys.Company.Builder.class);
        }

        // Construct using com.bonaparte.bean.CompanyProto.Companys.Company.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          id_ = 0L;

          name_ = "";

          memberCount_ = 0L;

          aliasName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.bonaparte.bean.CompanyProto.internal_static_Companys_Company_descriptor;
        }

        @java.lang.Override
        public com.bonaparte.bean.CompanyProto.Companys.Company getDefaultInstanceForType() {
          return com.bonaparte.bean.CompanyProto.Companys.Company.getDefaultInstance();
        }

        @java.lang.Override
        public com.bonaparte.bean.CompanyProto.Companys.Company build() {
          com.bonaparte.bean.CompanyProto.Companys.Company result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.bonaparte.bean.CompanyProto.Companys.Company buildPartial() {
          com.bonaparte.bean.CompanyProto.Companys.Company result = new com.bonaparte.bean.CompanyProto.Companys.Company(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          result.id_ = id_;
          result.name_ = name_;
          result.memberCount_ = memberCount_;
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            aliasName_ = aliasName_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.aliasName_ = aliasName_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.bonaparte.bean.CompanyProto.Companys.Company) {
            return mergeFrom((com.bonaparte.bean.CompanyProto.Companys.Company)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.bonaparte.bean.CompanyProto.Companys.Company other) {
          if (other == com.bonaparte.bean.CompanyProto.Companys.Company.getDefaultInstance()) return this;
          if (other.getId() != 0L) {
            setId(other.getId());
          }
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          if (other.getMemberCount() != 0L) {
            setMemberCount(other.getMemberCount());
          }
          if (!other.aliasName_.isEmpty()) {
            if (aliasName_.isEmpty()) {
              aliasName_ = other.aliasName_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureAliasNameIsMutable();
              aliasName_.addAll(other.aliasName_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.bonaparte.bean.CompanyProto.Companys.Company parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.bonaparte.bean.CompanyProto.Companys.Company) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private long id_ ;
        /**
         * <code>int64 id = 1;</code>
         */
        public long getId() {
          return id_;
        }
        /**
         * <code>int64 id = 1;</code>
         */
        public Builder setId(long value) {
          
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 id = 1;</code>
         */
        public Builder clearId() {
          
          id_ = 0L;
          onChanged();
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>string name = 2;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string name = 2;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string name = 2;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string name = 2;</code>
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>string name = 2;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }

        private long memberCount_ ;
        /**
         * <code>int64 memberCount = 3;</code>
         */
        public long getMemberCount() {
          return memberCount_;
        }
        /**
         * <code>int64 memberCount = 3;</code>
         */
        public Builder setMemberCount(long value) {
          
          memberCount_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 memberCount = 3;</code>
         */
        public Builder clearMemberCount() {
          
          memberCount_ = 0L;
          onChanged();
          return this;
        }

        private com.google.protobuf.LazyStringList aliasName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureAliasNameIsMutable() {
          if (!((bitField0_ & 0x00000008) == 0x00000008)) {
            aliasName_ = new com.google.protobuf.LazyStringArrayList(aliasName_);
            bitField0_ |= 0x00000008;
           }
        }
        /**
         * <code>repeated string aliasName = 4;</code>
         */
        public com.google.protobuf.ProtocolStringList
            getAliasNameList() {
          return aliasName_.getUnmodifiableView();
        }
        /**
         * <code>repeated string aliasName = 4;</code>
         */
        public int getAliasNameCount() {
          return aliasName_.size();
        }
        /**
         * <code>repeated string aliasName = 4;</code>
         */
        public java.lang.String getAliasName(int index) {
          return aliasName_.get(index);
        }
        /**
         * <code>repeated string aliasName = 4;</code>
         */
        public com.google.protobuf.ByteString
            getAliasNameBytes(int index) {
          return aliasName_.getByteString(index);
        }
        /**
         * <code>repeated string aliasName = 4;</code>
         */
        public Builder setAliasName(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureAliasNameIsMutable();
          aliasName_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string aliasName = 4;</code>
         */
        public Builder addAliasName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureAliasNameIsMutable();
          aliasName_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string aliasName = 4;</code>
         */
        public Builder addAllAliasName(
            java.lang.Iterable<java.lang.String> values) {
          ensureAliasNameIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, aliasName_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string aliasName = 4;</code>
         */
        public Builder clearAliasName() {
          aliasName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string aliasName = 4;</code>
         */
        public Builder addAliasNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          ensureAliasNameIsMutable();
          aliasName_.add(value);
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Companys.Company)
      }

      // @@protoc_insertion_point(class_scope:Companys.Company)
      private static final com.bonaparte.bean.CompanyProto.Companys.Company DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.bonaparte.bean.CompanyProto.Companys.Company();
      }

      public static com.bonaparte.bean.CompanyProto.Companys.Company getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Company>
          PARSER = new com.google.protobuf.AbstractParser<Company>() {
        @java.lang.Override
        public Company parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Company(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Company> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Company> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.bonaparte.bean.CompanyProto.Companys.Company getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int COMPANYS_FIELD_NUMBER = 1;
    private java.util.List<com.bonaparte.bean.CompanyProto.Companys.Company> companys_;
    /**
     * <code>repeated .Companys.Company companys = 1;</code>
     */
    public java.util.List<com.bonaparte.bean.CompanyProto.Companys.Company> getCompanysList() {
      return companys_;
    }
    /**
     * <code>repeated .Companys.Company companys = 1;</code>
     */
    public java.util.List<? extends com.bonaparte.bean.CompanyProto.Companys.CompanyOrBuilder> 
        getCompanysOrBuilderList() {
      return companys_;
    }
    /**
     * <code>repeated .Companys.Company companys = 1;</code>
     */
    public int getCompanysCount() {
      return companys_.size();
    }
    /**
     * <code>repeated .Companys.Company companys = 1;</code>
     */
    public com.bonaparte.bean.CompanyProto.Companys.Company getCompanys(int index) {
      return companys_.get(index);
    }
    /**
     * <code>repeated .Companys.Company companys = 1;</code>
     */
    public com.bonaparte.bean.CompanyProto.Companys.CompanyOrBuilder getCompanysOrBuilder(
        int index) {
      return companys_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < companys_.size(); i++) {
        output.writeMessage(1, companys_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < companys_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, companys_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bonaparte.bean.CompanyProto.Companys)) {
        return super.equals(obj);
      }
      com.bonaparte.bean.CompanyProto.Companys other = (com.bonaparte.bean.CompanyProto.Companys) obj;

      boolean result = true;
      result = result && getCompanysList()
          .equals(other.getCompanysList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCompanysCount() > 0) {
        hash = (37 * hash) + COMPANYS_FIELD_NUMBER;
        hash = (53 * hash) + getCompanysList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bonaparte.bean.CompanyProto.Companys parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bonaparte.bean.CompanyProto.Companys parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bonaparte.bean.CompanyProto.Companys parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bonaparte.bean.CompanyProto.Companys parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bonaparte.bean.CompanyProto.Companys parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bonaparte.bean.CompanyProto.Companys parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bonaparte.bean.CompanyProto.Companys parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bonaparte.bean.CompanyProto.Companys parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bonaparte.bean.CompanyProto.Companys parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bonaparte.bean.CompanyProto.Companys parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bonaparte.bean.CompanyProto.Companys parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bonaparte.bean.CompanyProto.Companys parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bonaparte.bean.CompanyProto.Companys prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Companys}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Companys)
        com.bonaparte.bean.CompanyProto.CompanysOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bonaparte.bean.CompanyProto.internal_static_Companys_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bonaparte.bean.CompanyProto.internal_static_Companys_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bonaparte.bean.CompanyProto.Companys.class, com.bonaparte.bean.CompanyProto.Companys.Builder.class);
      }

      // Construct using com.bonaparte.bean.CompanyProto.Companys.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCompanysFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (companysBuilder_ == null) {
          companys_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          companysBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bonaparte.bean.CompanyProto.internal_static_Companys_descriptor;
      }

      @java.lang.Override
      public com.bonaparte.bean.CompanyProto.Companys getDefaultInstanceForType() {
        return com.bonaparte.bean.CompanyProto.Companys.getDefaultInstance();
      }

      @java.lang.Override
      public com.bonaparte.bean.CompanyProto.Companys build() {
        com.bonaparte.bean.CompanyProto.Companys result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bonaparte.bean.CompanyProto.Companys buildPartial() {
        com.bonaparte.bean.CompanyProto.Companys result = new com.bonaparte.bean.CompanyProto.Companys(this);
        int from_bitField0_ = bitField0_;
        if (companysBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            companys_ = java.util.Collections.unmodifiableList(companys_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.companys_ = companys_;
        } else {
          result.companys_ = companysBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bonaparte.bean.CompanyProto.Companys) {
          return mergeFrom((com.bonaparte.bean.CompanyProto.Companys)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bonaparte.bean.CompanyProto.Companys other) {
        if (other == com.bonaparte.bean.CompanyProto.Companys.getDefaultInstance()) return this;
        if (companysBuilder_ == null) {
          if (!other.companys_.isEmpty()) {
            if (companys_.isEmpty()) {
              companys_ = other.companys_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCompanysIsMutable();
              companys_.addAll(other.companys_);
            }
            onChanged();
          }
        } else {
          if (!other.companys_.isEmpty()) {
            if (companysBuilder_.isEmpty()) {
              companysBuilder_.dispose();
              companysBuilder_ = null;
              companys_ = other.companys_;
              bitField0_ = (bitField0_ & ~0x00000001);
              companysBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCompanysFieldBuilder() : null;
            } else {
              companysBuilder_.addAllMessages(other.companys_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bonaparte.bean.CompanyProto.Companys parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bonaparte.bean.CompanyProto.Companys) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.bonaparte.bean.CompanyProto.Companys.Company> companys_ =
        java.util.Collections.emptyList();
      private void ensureCompanysIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          companys_ = new java.util.ArrayList<com.bonaparte.bean.CompanyProto.Companys.Company>(companys_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.bonaparte.bean.CompanyProto.Companys.Company, com.bonaparte.bean.CompanyProto.Companys.Company.Builder, com.bonaparte.bean.CompanyProto.Companys.CompanyOrBuilder> companysBuilder_;

      /**
       * <code>repeated .Companys.Company companys = 1;</code>
       */
      public java.util.List<com.bonaparte.bean.CompanyProto.Companys.Company> getCompanysList() {
        if (companysBuilder_ == null) {
          return java.util.Collections.unmodifiableList(companys_);
        } else {
          return companysBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Companys.Company companys = 1;</code>
       */
      public int getCompanysCount() {
        if (companysBuilder_ == null) {
          return companys_.size();
        } else {
          return companysBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Companys.Company companys = 1;</code>
       */
      public com.bonaparte.bean.CompanyProto.Companys.Company getCompanys(int index) {
        if (companysBuilder_ == null) {
          return companys_.get(index);
        } else {
          return companysBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Companys.Company companys = 1;</code>
       */
      public Builder setCompanys(
          int index, com.bonaparte.bean.CompanyProto.Companys.Company value) {
        if (companysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCompanysIsMutable();
          companys_.set(index, value);
          onChanged();
        } else {
          companysBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Companys.Company companys = 1;</code>
       */
      public Builder setCompanys(
          int index, com.bonaparte.bean.CompanyProto.Companys.Company.Builder builderForValue) {
        if (companysBuilder_ == null) {
          ensureCompanysIsMutable();
          companys_.set(index, builderForValue.build());
          onChanged();
        } else {
          companysBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Companys.Company companys = 1;</code>
       */
      public Builder addCompanys(com.bonaparte.bean.CompanyProto.Companys.Company value) {
        if (companysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCompanysIsMutable();
          companys_.add(value);
          onChanged();
        } else {
          companysBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Companys.Company companys = 1;</code>
       */
      public Builder addCompanys(
          int index, com.bonaparte.bean.CompanyProto.Companys.Company value) {
        if (companysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCompanysIsMutable();
          companys_.add(index, value);
          onChanged();
        } else {
          companysBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Companys.Company companys = 1;</code>
       */
      public Builder addCompanys(
          com.bonaparte.bean.CompanyProto.Companys.Company.Builder builderForValue) {
        if (companysBuilder_ == null) {
          ensureCompanysIsMutable();
          companys_.add(builderForValue.build());
          onChanged();
        } else {
          companysBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Companys.Company companys = 1;</code>
       */
      public Builder addCompanys(
          int index, com.bonaparte.bean.CompanyProto.Companys.Company.Builder builderForValue) {
        if (companysBuilder_ == null) {
          ensureCompanysIsMutable();
          companys_.add(index, builderForValue.build());
          onChanged();
        } else {
          companysBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Companys.Company companys = 1;</code>
       */
      public Builder addAllCompanys(
          java.lang.Iterable<? extends com.bonaparte.bean.CompanyProto.Companys.Company> values) {
        if (companysBuilder_ == null) {
          ensureCompanysIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, companys_);
          onChanged();
        } else {
          companysBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Companys.Company companys = 1;</code>
       */
      public Builder clearCompanys() {
        if (companysBuilder_ == null) {
          companys_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          companysBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Companys.Company companys = 1;</code>
       */
      public Builder removeCompanys(int index) {
        if (companysBuilder_ == null) {
          ensureCompanysIsMutable();
          companys_.remove(index);
          onChanged();
        } else {
          companysBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Companys.Company companys = 1;</code>
       */
      public com.bonaparte.bean.CompanyProto.Companys.Company.Builder getCompanysBuilder(
          int index) {
        return getCompanysFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Companys.Company companys = 1;</code>
       */
      public com.bonaparte.bean.CompanyProto.Companys.CompanyOrBuilder getCompanysOrBuilder(
          int index) {
        if (companysBuilder_ == null) {
          return companys_.get(index);  } else {
          return companysBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Companys.Company companys = 1;</code>
       */
      public java.util.List<? extends com.bonaparte.bean.CompanyProto.Companys.CompanyOrBuilder> 
           getCompanysOrBuilderList() {
        if (companysBuilder_ != null) {
          return companysBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(companys_);
        }
      }
      /**
       * <code>repeated .Companys.Company companys = 1;</code>
       */
      public com.bonaparte.bean.CompanyProto.Companys.Company.Builder addCompanysBuilder() {
        return getCompanysFieldBuilder().addBuilder(
            com.bonaparte.bean.CompanyProto.Companys.Company.getDefaultInstance());
      }
      /**
       * <code>repeated .Companys.Company companys = 1;</code>
       */
      public com.bonaparte.bean.CompanyProto.Companys.Company.Builder addCompanysBuilder(
          int index) {
        return getCompanysFieldBuilder().addBuilder(
            index, com.bonaparte.bean.CompanyProto.Companys.Company.getDefaultInstance());
      }
      /**
       * <code>repeated .Companys.Company companys = 1;</code>
       */
      public java.util.List<com.bonaparte.bean.CompanyProto.Companys.Company.Builder> 
           getCompanysBuilderList() {
        return getCompanysFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.bonaparte.bean.CompanyProto.Companys.Company, com.bonaparte.bean.CompanyProto.Companys.Company.Builder, com.bonaparte.bean.CompanyProto.Companys.CompanyOrBuilder> 
          getCompanysFieldBuilder() {
        if (companysBuilder_ == null) {
          companysBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.bonaparte.bean.CompanyProto.Companys.Company, com.bonaparte.bean.CompanyProto.Companys.Company.Builder, com.bonaparte.bean.CompanyProto.Companys.CompanyOrBuilder>(
                  companys_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          companys_ = null;
        }
        return companysBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Companys)
    }

    // @@protoc_insertion_point(class_scope:Companys)
    private static final com.bonaparte.bean.CompanyProto.Companys DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bonaparte.bean.CompanyProto.Companys();
    }

    public static com.bonaparte.bean.CompanyProto.Companys getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Companys>
        PARSER = new com.google.protobuf.AbstractParser<Companys>() {
      @java.lang.Override
      public Companys parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Companys(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Companys> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Companys> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bonaparte.bean.CompanyProto.Companys getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Companys_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Companys_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Companys_Company_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Companys_Company_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n src/main/resources/Company.proto\"|\n\010Co" +
      "mpanys\022#\n\010companys\030\001 \003(\0132\021.Companys.Comp" +
      "any\032K\n\007Company\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t" +
      "\022\023\n\013memberCount\030\003 \001(\003\022\021\n\taliasName\030\004 \003(\t" +
      "B\"\n\022com.bonaparte.beanB\014CompanyProtob\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Companys_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Companys_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Companys_descriptor,
        new java.lang.String[] { "Companys", });
    internal_static_Companys_Company_descriptor =
      internal_static_Companys_descriptor.getNestedTypes().get(0);
    internal_static_Companys_Company_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Companys_Company_descriptor,
        new java.lang.String[] { "Id", "Name", "MemberCount", "AliasName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
